export const datas = [
  {
    fromWhere: "Ankara",
    toWhere: "İzmir",
    date: "2023-10-13",
    departureTime: "09:30",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 170.0,
    company: "Örnek Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3531-sm.png",
  },
  {
    fromWhere: "Ankara",
    toWhere: "İzmir",
    date: "2023-10-14",
    departureTime: "09:30",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 170.0,
    company: "Örnek Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/2264-sm.png",
  },
  {
    fromWhere: "Ankara",
    toWhere: "Bursa",
    date: "2023-10-14",
    departureTime: "09:30",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 170.0,
    company: "Örnek Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/2289-sm.png",
  },
  {
    fromWhere: "Ankara",
    toWhere: "Bursa",
    date: "2023-10-15",
    departureTime: "09:30",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 170.0,
    company: "Örnek Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3537-sm.png",
  },
  {
    fromWhere: "İstanbul",
    toWhere: "İzmir",
    date: "2023-10-13",
    departureTime: "11:15",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 180.0,
    company: "Başka Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/2223-sm.png",
  },
  {
    fromWhere: "İstanbul",
    toWhere: "İzmir",
    date: "2023-10-14",
    departureTime: "11:15",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 180.0,
    company: "Başka Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/1234-sm.png",
  },
  {
    fromWhere: "İstanbul",
    toWhere: "Bursa",
    date: "2023-10-14",
    departureTime: "11:15",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 180.0,
    company: "Başka Hava Yolları",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/1234-sm.png",
  },
  {
    fromWhere: "İstanbul",
    toWhere: "Bursa",
    date: "2023-10-15",
    departureTime: "09:30",
    totalTime: "3.5 saat",
    emptySeats: 15,
    price: 165.0,
    company: "Diğer Hava Yolu Şirketi",
    companyImage: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/5678-sm.png",
  },
];
