export const datas = [
    {
      kalkisOtogari: "Ankara Otogarı",
      varisOtogari: "İstanbul Otogarı",
      kalkisSehri: "Ankara",
      varisSehri: "İstanbul",
      tarih: "2023-10-16",
      kalkisSaat: "09:30",
      varisSaat: "12:30",
      sure: "3.5 saat",
      bosKoltukSayisi: 45,
      fiyat: 170.0,
      firma: "Örnek Hava Yolları",
      firmaResmi: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3531-sm.png",
    },
    {
      kalkisOtogari: "İstanbul Havalimanı",
      varisOtogari: "Ankara Otogarı",
      kalkisSehri: "İstanbul",
      varisSehri: "Ankara",
      tarih: "2023-10-15",
      kalkisSaat: "10:30",
      varisSaat: "13:30",
      sure: "3 saat",
      bosKoltukSayisi: 40,
      fiyat: 160.0,
      firma: "Başka Havayolları",
      firmaResmi: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3421-sm.png",
    },
    {
      kalkisOtogari: "Ankara Otogarı",
      varisOtogari: "İstanbul Havalimanı",
      kalkisSehri: "Ankara",
      varisSehri: "İstanbul",
      tarih: "2023-10-17",
      kalkisSaat: "11:30",
      varisSaat: "14:30",
      sure: "3 saat",
      bosKoltukSayisi: 48,
      fiyat: 155.0,
      firma: "Farklı Havayolları",
      firmaResmi: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3381-sm.png",
    },
    {
      kalkisOtogari: "Ankara Otogarı",
      varisOtogari: "İstanbul Otogarı",
      kalkisSehri: "Ankara",
      varisSehri: "İstanbul",
      tarih: "2023-10-16",
      kalkisSaat: "12:30",
      varisSaat: "15:30",
      sure: "3 saat",
      bosKoltukSayisi: 49,
      fiyat: 165.0,
      firma: "Başka Bir Havayolu",
      firmaResmi: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/3555-sm.png",
    },
    {
      kalkisOtogari: "İstanbul Otogarı",
      varisOtogari: "Ankara Otogarı",
      kalkisSehri: "İstanbul",
      varisSehri: "Ankara",
      tarih: "2023-10-17",
      kalkisSaat: "13:30",
      varisSaat: "16:30",
      sure: "3 saat",
      bosKoltukSayisi: 47,
      fiyat: 175.0,
      firma: "Başka Havayolu Şirketi",
      firmaResmi: "https://s3.eu-central-1.amazonaws.com/static.obilet.com/images/partner/330-sm.png",
    },
  ];
  